# Generated by Django 5.1.3 on 2024-12-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockdetails',
            old_name='current_price',
            new_name='Gain',
        ),
        migrations.RenameField(
            model_name='stockdetails',
            old_name='created_at',
            new_name='Signal_Closed',
        ),
        migrations.RenameField(
            model_name='stockdetails',
            old_name='change_percentage',
            new_name='Sold_Above',
        ),
        migrations.RenameField(
            model_name='stockdetails',
            old_name='highest_price',
            new_name='bought_below',
        ),
        migrations.RemoveField(
            model_name='stockdetails',
            name='lowest_price',
        ),
        migrations.AddField(
            model_name='stockdetails',
            name='Signal_Sent',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
