# Generated by Django 5.1.3 on 2024-12-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_sold_above_stockdetails_gain_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=100)),
                ('stock_exchange', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gain', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
