# Generated by Django 5.1.4 on 2024-12-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradDt', models.DateField()),
                ('BizDt', models.DateField()),
                ('Sgmt', models.CharField(max_length=255)),
                ('Src', models.CharField(max_length=255)),
                ('FinInstrmTp', models.CharField(max_length=255)),
                ('FinInstrmId', models.CharField(max_length=255)),
                ('ISIN', models.CharField(max_length=255)),
                ('TckrSymb', models.CharField(max_length=255)),
                ('SctySrs', models.CharField(max_length=255)),
                ('FinInstrmNm', models.CharField(max_length=255)),
                ('OpnPric', models.FloatField()),
                ('HghPric', models.FloatField()),
                ('LwPric', models.FloatField()),
                ('ClsPric', models.FloatField()),
                ('LastPric', models.FloatField()),
                ('PrvsClsgPric', models.FloatField()),
            ],
        ),
    ]
